# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wacki
baseurl: "" # the subpath of your site, e.g. /blog
url:			"http://wacki.me" # the base hostname & protocol for your site

permalink:		'/blog/:year/:month/:title/'

excerpt_separator: <!--more-->

collections:
  portfolio:
    output: true
    permalink: '/portfolio/:path/'

# Author
author:
  name: Marc Wacker
  email: wackiblog@gmail.com
  about_me: > # this means to ignore newlines until "baseurl:"
    I am a Programmer / Technical Artist living and working in Vancouver, Canada. This is my personal blog and portfolio where I infrequently post about the stuff I do.
  twitter: wacki
  github: wacki
  twitch: wackitv
  youtube: thewackii
  linkedin: marc-wacker
  facebook:
  stackoverflow:
  disqus-shortname: wacki

description: > 
  Personal blog of Marc Wacker.

# Build settings
markdown: kramdown
highlighter: rouge



defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: project