# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wacki
baseurl: "" # the subpath of your site, e.g. /blog
url:			"http://wacki.me" # the base hostname & protocol for your site

permalink:		'/blog/:year/:month/:title/'

excerpt_separator: <!--more-->

collections:
  portfolio:
    output: true
    permalink: '/portfolio/:path/'

# Author
author:
  name: Marc Wacker
  email: wackiblog@gmail.com
  about_me: > # this means to ignore newlines until "baseurl:"
    I am a software engineer currently studying Game Design at VFS in Vancouver, Canada. 
    Excited to make my first steps towards being a full time game dev. This site acts as my personal blog and portfolio.
  twitter: wacki
  github: wacki
  twitch: wackitv
  youtube: thewackii
  linkedin: marc-wacker
  facebook:
  stackoverflow:
  disqus-shortname: wacki

description: > 
  Personal blog of Marc Wacker. I use this blog to document my learning process
  in different areas. Mostly game development. I might also use it for other stuff.

# Build settings
markdown: kramdown
highlighter: rouge



defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: project